import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  images: {
    // Renditions are pre-generated by scripts/prepare-assets.mjs; the custom
    // loader maps requested widths onto them (no runtime optimizer, so the
    // whole site stays `output: 'export'`-compatible).
    loader: "custom",
    loaderFile: "./src/lib/imageLoader.ts",
    deviceSizes: [420, 640, 828, 1080, 1440],
    imageSizes: [128, 256],
  },
};

export default nextConfig;
