/**
 * Single source of truth for everything commercial.
 * Edit values here — components never hardcode them.
 *
 * Values are validated by the zod schema in ./site.config.schema.ts, which the
 * root layout (a server component) runs at build time — a typo fails
 * `next build`, not the page. The schema lives in a separate file so zod never
 * reaches the client bundle. See DECISIONS.md.
 */
const rawConfig = {
  store: {
    name: "Casquette Store",
    productTitle: "Casquette Lacoste original",
    shortDescription:
      "Coupe ajustée, coton peigné, finition soignée. Une casquette qui va avec tout.",
    /**
     * Brand mark for the header. `null` falls back to the text wordmark.
     * Generated by `npm run assets` (trimmed + recoloured to --primary);
     * the script prints these numbers whenever the source logo changes.
     */
    logo: { src: "/images/logo.png", width: 83, height: 80 } as {
      src: string;
      width: number;
      height: number;
    } | null,
    /** International format without '+', e.g. '213550123456'. Empty string hides the floating button. */
    whatsapp: "",
    email: "",
  },
  currency: { code: "DZD", suffix: "DA", separator: " ", decimals: 0 },
  pricing: {
    price: 12000,
    /** null hides the strikethrough */
    compareAtPrice: 15000 as number | null,
    /**
     * Unconditional free delivery in all 58 wilayas. When true, computeTotals()
     * returns shipping 0 whatever the wilaya or delivery type, and the UI says
     * "Gratuite" rather than a zero price. The per-wilaya prices in
     * data/wilayas.ts are left intact — flip this back to false and every
     * original rate returns with no other edit.
     */
    freeShipping: true,
    /** Spend-based free shipping; ignored while freeShipping is true. */
    freeShippingThreshold: null as number | null,
    /** Applied to unit price. Sorted check enforced by schema. Empty = flat price. */
    quantityDiscounts: [] as { minQty: number; unitPrice: number }[],
  },
  /**
   * `swatch` is the real product colour, sampled from the photographs — it is
   * NOT a brand colour and must stay distinct from --primary, or the chip reads
   * as UI chrome. It also drives LAB variant matching in prepare-assets.mjs, so
   * re-sample (don't hand-pick) if the photos change.
   */
  colors: [
    { id: "blue", label: "Bleu", swatch: "#253043" },
    { id: "green", label: "Vert", swatch: "#3E5044" },
    { id: "black", label: "Noir", swatch: "#1C1917" },
  ],
  quantity: { min: 1, max: 10, default: 1 },
  delivery: {
    types: [
      {
        id: "home",
        label: "Livraison à domicile",
        hint: "Le livreur vous appelle",
      },
      {
        id: "desk",
        label: "Retrait au bureau",
        hint: "Moins cher, agence la plus proche",
      },
    ],
    default: "home",
  },
  shipping: {
    /** Used for any wilaya missing data in src/data/wilayas.ts */
    fallbackHome: 800,
    fallbackDesk: 450,
  },
  validation: {
    phone: {
      pattern: "^(?:\\+213|00213|0)([5-7])[0-9]{8}$",
      normalize: true,
      minLength: 9,
    },
    name: { min: 3, max: 60 },
  },
  order: {
    endpoint: process.env.NEXT_PUBLIC_ORDER_ENDPOINT ?? "",
    idPrefix: "CAP",
    timeoutMs: 12000,
    retries: 2,
    defaultStatus: "New",
  },
  seo: {
    /**
     * Canonical origin, no trailing slash. Drives canonical URLs, OG images,
     * JSON-LD and the sitemap. Netlify/Vercel inject their own URL, so the
     * literal below is only the local fallback — set NEXT_PUBLIC_SITE_URL (or
     * let Netlify's URL var through) once you have the real domain.
     */
    siteUrl:
      process.env.NEXT_PUBLIC_SITE_URL ??
      process.env.URL ?? // Netlify: primary site URL
      "http://localhost:3000",
    locale: "fr_DZ",
  },
} as const;

export const config = rawConfig;

export type SiteConfig = typeof config;
export type ColorId = SiteConfig["colors"][number]["id"];
export type DeliveryTypeId = SiteConfig["delivery"]["types"][number]["id"];
