// GENERATED by scripts/prepare-assets.mjs — do not edit by hand.
// Rerun `npm run assets` after changing the photo folder.
import type { ProductImage } from "@/types";

export const HERO_IMAGE: ProductImage = 
{
    id: "img-ff90b400a4",
    alt: "Casquette Lacoste original coloris bleu — vue principale",
    width: 866,
    height: 1104,
    variant: "blue",
    role: "hero",
    lqip: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAZABQDASIAAhEBAxEB/8QAGgAAAQUBAAAAAAAAAAAAAAAAAAIDBAUGB//EAB8QAAICAgIDAQAAAAAAAAAAAAECAAMEEQUSBhMxUf/EABYBAQEBAAAAAAAAAAAAAAAAAAEAAv/EABYRAQEBAAAAAAAAAAAAAAAAAAARAf/aAAwDAQACEQMRAD8A1tli1IWc6AkWrk8a2zotg3K7ymx0wh0JG/syWPayXVlWO9zWYK6VCM4hLY1Zb6RCZKNy2Cc/G9YOjKDH8ZvW5S7DqDNdCNUIqT11Kn4NQi4QT//Z",
    src: {
      avif: "/images/img-ff90b400a4-{w}.avif",
      webp: "/images/img-ff90b400a4-{w}.webp",
      fallback: "/images/img-ff90b400a4-1080.jpg",
    },
    order: 0,
  };

export const GALLERY_IMAGES: ProductImage[] = [
  {
    id: "img-b16c28249a",
    alt: "Casquette Lacoste original coloris bleu — vue 1",
    width: 938,
    height: 1080,
    variant: "blue",
    role: "gallery",
    lqip: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAXABQDASIAAhEBAxEB/8QAGQABAAIDAAAAAAAAAAAAAAAAAAQGAQIF/8QAIBAAAgICAQUBAAAAAAAAAAAAAQIAAwQREgUGEyExFf/EABUBAQEAAAAAAAAAAAAAAAAAAAAB/8QAFhEBAQEAAAAAAAAAAAAAAAAAABEh/9oADAMBAAIRAxEAPwC1XZFVC7tYKIoyasgbrcNK73VRlWMrVAlB91Od0POsxMkLaG0fWpZiVeImqOHQMPhiRWWVWGmAIkf8/G58vEu4iBJAAGh6ERED/9k=",
    src: {
      avif: "/images/img-b16c28249a-{w}.avif",
      webp: "/images/img-b16c28249a-{w}.webp",
      fallback: "/images/img-b16c28249a-1080.jpg",
    },
    order: 1,
  },
  {
    id: "img-b96bb9345a",
    alt: "Casquette Lacoste original coloris noir — vue 1",
    width: 884,
    height: 1094,
    variant: "black",
    role: "gallery",
    lqip: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAZABQDASIAAhEBAxEB/8QAGgAAAQUBAAAAAAAAAAAAAAAAAAEDBAUGB//EACAQAAEFAAICAwAAAAAAAAAAAAEAAgMEERIxBhMFIUH/xAAUAQEAAAAAAAAAAAAAAAAAAAAA/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8A1dieOvGXyHAFXV/nqs83rDsJ6UXywvFIcTg/VkIX5PFw+jqDpwOjQhM1CTVjJ74oQN36Ud6H1ydKrh8YrRSh5O4dV8hAjGhjQ0dBCVCD/9k=",
    src: {
      avif: "/images/img-b96bb9345a-{w}.avif",
      webp: "/images/img-b96bb9345a-{w}.webp",
      fallback: "/images/img-b96bb9345a-1080.jpg",
    },
    order: 2,
  },
  {
    id: "img-cdfdfc74ec",
    alt: "Casquette Lacoste original coloris noir — vue 2",
    width: 920,
    height: 1174,
    variant: "black",
    role: "gallery",
    lqip: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAaABQDASIAAhEBAxEB/8QAGAABAQEBAQAAAAAAAAAAAAAAAAYCBAX/xAAhEAABBAEDBQAAAAAAAAAAAAABAAIDEQQFBjESEyFBUf/EABQBAQAAAAAAAAAAAAAAAAAAAAD/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCvRTO5tUyMSRscNgH2sbf1l80nanfd8WgqUQG+EQcubp8GawiVgJ+ryItsRxTiRshABvwqFEGY29DA27oItIg//9k=",
    src: {
      avif: "/images/img-cdfdfc74ec-{w}.avif",
      webp: "/images/img-cdfdfc74ec-{w}.webp",
      fallback: "/images/img-cdfdfc74ec-1080.jpg",
    },
    order: 3,
  },
  {
    id: "img-92cb1ae997",
    alt: "Casquette Lacoste original coloris bleu — vue 2",
    width: 906,
    height: 1150,
    variant: "blue",
    role: "gallery",
    lqip: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAZABQDASIAAhEBAxEB/8QAGQABAAMBAQAAAAAAAAAAAAAAAAEFBgME/8QAHxAAAwACAgMBAQAAAAAAAAAAAAECBAUDEQYSMSEi/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAH/xAAVEQEBAAAAAAAAAAAAAAAAAAAAEf/aAAwDAQACEQMRAD8A14KLe7usC1x8a/pnm1fkq5b9Mj87+MsStMCIpXKqfjBFVe00nFsbVW+mjnheOYuNSpr2aLkARMqZUyukgSAP/9k=",
    src: {
      avif: "/images/img-92cb1ae997-{w}.avif",
      webp: "/images/img-92cb1ae997-{w}.webp",
      fallback: "/images/img-92cb1ae997-1080.jpg",
    },
    order: 4,
  },
  {
    id: "img-33f70d1636",
    alt: "Casquette Lacoste original coloris noir — vue 3",
    width: 900,
    height: 1060,
    variant: "black",
    role: "gallery",
    lqip: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAYABQDASIAAhEBAxEB/8QAGAABAAMBAAAAAAAAAAAAAAAAAAEEBgL/xAAeEAACAgMAAwEAAAAAAAAAAAAAAQIDBAURBhMhYf/EABQBAQAAAAAAAAAAAAAAAAAAAAD/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDXgzHku4uxLVTT8/SnqPI71YoXJzTA2YOKp+yuM0udQAq5mrxs2SldDrIx9TiY77CpdAAvJJLi+IAAf//Z",
    src: {
      avif: "/images/img-33f70d1636-{w}.avif",
      webp: "/images/img-33f70d1636-{w}.webp",
      fallback: "/images/img-33f70d1636-1080.jpg",
    },
    order: 5,
  },
  {
    id: "img-705955b4ef",
    alt: "Casquette Lacoste original coloris bleu — gros plan sur la matière",
    width: 952,
    height: 1186,
    variant: "blue",
    role: "detail",
    lqip: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAZABQDASIAAhEBAxEB/8QAGAABAQEBAQAAAAAAAAAAAAAAAgAEAQX/xAAeEAACAgICAwAAAAAAAAAAAAAAAQIRAzEEEhMhQf/EABYBAQEBAAAAAAAAAAAAAAAAAAECAP/EABcRAQEBAQAAAAAAAAAAAAAAAAARAQL/2gAMAwEAAhEDEQA/APBi29Ddx2qHwZQj7lVmrI8WR3JpFb3NgjD2IORpTajoi0h460y6N/WM6Yh0IRGD/9k=",
    src: {
      avif: "/images/img-705955b4ef-{w}.avif",
      webp: "/images/img-705955b4ef-{w}.webp",
      fallback: "/images/img-705955b4ef-1080.jpg",
    },
    order: 6,
  },
];

/** Variants that actually have at least one photo (drives chip rendering). */
export const VARIANTS_WITH_PHOTOS: string[] = ["blue","black"];

/** Best image per variant, for hero cross-fade + color chips. */
export const VARIANT_IMAGES: Record<string, ProductImage> = {
  "blue": {
    id: "img-ff90b400a4",
    alt: "Casquette Lacoste original coloris bleu — vue principale",
    width: 866,
    height: 1104,
    variant: "blue",
    role: "hero",
    lqip: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAZABQDASIAAhEBAxEB/8QAGgAAAQUBAAAAAAAAAAAAAAAAAAIDBAUGB//EAB8QAAICAgIDAQAAAAAAAAAAAAECAAMEEQUSBhMxUf/EABYBAQEBAAAAAAAAAAAAAAAAAAEAAv/EABYRAQEBAAAAAAAAAAAAAAAAAAARAf/aAAwDAQACEQMRAD8A1tli1IWc6AkWrk8a2zotg3K7ymx0wh0JG/syWPayXVlWO9zWYK6VCM4hLY1Zb6RCZKNy2Cc/G9YOjKDH8ZvW5S7DqDNdCNUIqT11Kn4NQi4QT//Z",
    src: {
      avif: "/images/img-ff90b400a4-{w}.avif",
      webp: "/images/img-ff90b400a4-{w}.webp",
      fallback: "/images/img-ff90b400a4-1080.jpg",
    },
    order: 0,
  },
  "black": {
    id: "img-b96bb9345a",
    alt: "Casquette Lacoste original coloris noir — vue 1",
    width: 884,
    height: 1094,
    variant: "black",
    role: "gallery",
    lqip: "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAZABQDASIAAhEBAxEB/8QAGgAAAQUBAAAAAAAAAAAAAAAAAAEDBAUGB//EACAQAAEFAAICAwAAAAAAAAAAAAEAAgMEERIxBhMFIUH/xAAUAQEAAAAAAAAAAAAAAAAAAAAA/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8A1dieOvGXyHAFXV/nqs83rDsJ6UXywvFIcTg/VkIX5PFw+jqDpwOjQhM1CTVjJ74oQN36Ud6H1ydKrh8YrRSh5O4dV8hAjGhjQ0dBCVCD/9k=",
    src: {
      avif: "/images/img-b96bb9345a-{w}.avif",
      webp: "/images/img-b96bb9345a-{w}.webp",
      fallback: "/images/img-b96bb9345a-1080.jpg",
    },
    order: 2,
  },
};

